apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: inferentia-inf2
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: Never
  template:
    metadata:
      labels:
        type: karpenter
        instanceType: inferentia-inf2
        provisionerType: Karpenter
        hub.jupyter.org/node-purpose: user
    spec:
      nodeClassRef:
        name: inferentia-inf2
      taints:
        - key: aws.amazon.com/neuron
          value: "true"
          effect: "NoSchedule"
        - key: hub.jupyter.org/dedicated
          operator: "Equal"
          value: "user"
          effect: "NoSchedule"
      requirements:
        - key: karpenter.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            # HIGHLIGHT
            - inf2
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: inferentia-inf2
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        volumeSize: 500Gi
        volumeType: gp3
  role: ${KARPENTER_NODE_ROLE}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${EKS_CLUSTER_NAME}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${EKS_CLUSTER_NAME}
  tags:
    app.kubernetes.io/created-by: eks-workshop
